apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: nginx-template
  project: giri
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx-template/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx-template/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
