apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-bitnami
  project: giri
spec:
  endpoint: https://charts.bitnami.com/bitnami
  options: {}
  type: Helm
status:
  projects:
  - projectId: 7w2lnkp
    repositoryId: q72dg2g
  webhookConfig:
    webhookSecret: 085a995bf232de3d08d4c80051e6beaa1a9657aeedebb9e1ded2e8c9a896ad4b
    webhookURL: https://console-giri-test.dev.rafay-edge.net/v2/config/webhook/repository/q72dg2g
