apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: cfg
  project: giri
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/cfg/nginx-15.4.2.tgz
    type: Helm
  namespace: trest1
