apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: giri
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx/nginx-15.4.2.tgz
    type: Helm
  namespace: workload-ns
