apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: ns-workload
  project: giri
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/ns-workload/consul-10.2.4.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: unmanaged
  placement:
    selector: rafay.dev/clusterName=giri-tb-test
