apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: xwing-app
  project: giri
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/xwing-app/xwing-app.yaml
    type: Yaml
  namespace: workload-ns
  placement:
    selector: rafay.dev/clusterName=giri-tb-test
