apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: giri-testbed
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCRXJ5TSsZdNbjJrP/Y9joZyb3UVKpCHKiT3tJFZPvoqLMKFg0J3Qi0qgh732f4jQQog33TP80sIaY9W8rZCzFQiWoOjxsjE6Y7bOZg1g17E6cINz4UhtVCDuZrKysSRF2dlJCOT8c47FCRri4p0PCF3bLygqXlfz+9uIOluApMC0kEyRU/vjQQBeOBLU50Wp4TLMYz2cMBetDK/hubeisSJROTw3IuHiced1/nnUM+9W0+XOyFlJzfRzuJVix7ljS0p8xpJ88+rumknKYiinYVYJKPVqEAnHyR72a+4wl5lUxU3X74aQaKgVJ1MXofg5r6tGRePokK4/h1IJWCIYUaVFR1j58WaJLAEoDQirRXLXR1AaVM/ZyC9fws5yJjyN2iEMoFGRzQA1gf7/6P8jM+Lk5kwMJsGoU=
  template:
    metadata:
      creationTimestamp: null
      name: giri-testbed
      namespace: default

